// ============================================================
// Every room has a card when somebody shares it
// ============================================================
//
// Found by asking a simple question: does Piano Night have an Open Graph
// image? It did not — it was the only entry page in the repo with no OG or
// Twitter tags at all, so every /piano-night link anybody pasted into a chat
// unfurled as a bare URL while Karaoke, Jam, Guitar Night and Glass all had
// designed cards.
//
// Nothing catches that. The pages are hand-written HTML outside the app, they
// are never rendered by a test, and a missing meta tag breaks nothing you can
// see locally. This is the check that says so.
//
// Each card is generated by a `scripts/generate-<room>-og.mjs` sibling, so a
// new room can copy one and stay consistent.

import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { parseHash } from '@/lib/hash-router'

const repo = resolve(__dirname, '../..')

/** Entry pages: the hand-written HTML at the repo root that Vite builds. */
const pages = readdirSync(repo)
  .filter((name) => name.endsWith('.html'))
  // The 3D range tester is a scratch harness, not a shared surface.
  .filter((name) => name !== 'vocal-range-test.html')
  .sort()

function read(name: string): string {
  return readFileSync(resolve(repo, name), 'utf8')
}

/** The `content` of the first matching meta tag, ignoring attribute order. */
function meta(html: string, key: string): string | undefined {
  const pattern = new RegExp(
    `<meta[^>]*(?:property|name)="${key}"[^>]*>|<meta[^>]*content="[^"]*"[^>]*(?:property|name)="${key}"[^>]*>`,
    's',
  )
  const tag = pattern.exec(html)?.[0]
  if (tag === undefined) {
    // Prettier splits long meta tags across lines with content last.
    const multi = new RegExp(
      `<meta\\s+(?:property|name)="${key}"\\s+content="([^"]*)"\\s*/?>`,
      's',
    ).exec(html)
    return multi?.[1]
  }
  return /content="([^"]*)"/s.exec(tag)?.[1]
}

describe('entry pages', () => {
  it('found the pages to check', () => {
    expect(pages.length).toBeGreaterThanOrEqual(6)
    expect(pages).toContain('piano-night.html')
    expect(pages).toContain('drum-night.html')
  })

  it.each(pages)('%s unfurls with a card', (name) => {
    const html = read(name)

    for (const key of [
      'og:title',
      'og:description',
      'og:url',
      'og:image',
      'og:image:width',
      'og:image:height',
      'og:image:alt',
      'twitter:card',
      'twitter:image',
    ]) {
      expect(meta(html, key), `${name} is missing ${key}`).toBeTruthy()
    }

    // The dimensions have to be true, not just present: an unfurler that
    // trusts them and gets a different aspect crops the card.
    expect(meta(html, 'og:image:width')).toBe('1200')
    expect(meta(html, 'og:image:height')).toBe('630')
    expect(meta(html, 'twitter:card')).toBe('summary_large_image')
  })

  it.each(pages)('%s points at an image that exists', (name) => {
    const image = meta(read(name), 'og:image')
    expect(image).toMatch(/^https:\/\/mercurypitch\.com\//)
    const file = resolve(
      repo,
      'public',
      image!.replace(/^https:\/\/[^/]+\//, ''),
    )
    expect(existsSync(file), `${image} has no file`).toBe(true)
  })

  it.each(pages)('%s twitter:image agrees with og:image', (name) => {
    const html = read(name)
    // Two URLs that drift is how one platform shows the old card forever.
    expect(meta(html, 'twitter:image')).toBe(meta(html, 'og:image'))
  })
})

describe('the card generators', () => {
  it('exist for every room-specific card', () => {
    // A card with no script is a card nobody can regenerate when the room's
    // art or copy changes.
    for (const room of [
      'karaoke',
      'jam',
      'guitar-night',
      'piano-night',
      'drum-night',
      'ear-lab',
    ]) {
      expect(
        existsSync(resolve(repo, `scripts/generate-${room}-og.mjs`)),
        `no generator for ${room}`,
      ).toBe(true)
    }
  })
})

// ============================================================
// A shared jam room has to land on the page with the card
// ============================================================
//
// Jam has had `jam-og.png` since the card set was built, wired into
// `jam.html` — which the server serves for `/jam` and `/jam-rooms`. But the
// link the room's own copy button produced was `${origin}/#/jam:ROOMID`: the
// ROOT path with a hash. Hashes are never sent to a server, so every invite
// anybody pasted into a chat was fetched as `/`, served `index.html`, and
// unfurled with the generic site image.
//
// The room worked. The card was there. The two never met.

describe('the jam room invite link', () => {
  const panel = readFileSync(
    resolve(repo, 'src/components/jam/JamPanel.tsx'),
    'utf8',
  )

  it('is built on a path the server can route', () => {
    expect(panel).toContain('`${window.location.origin}/jam#/jam:')
    // The old shape, which resolves to index.html.
    expect(panel).not.toContain('`${window.location.origin}/#/jam:')
  })

  it('keeps the hash the router already reads', () => {
    // Only the path moved. Changing the fragment would break every link
    // already in somebody's chat history.
    expect(panel).toMatch(/\/jam#\/jam:\$\{jamRoomId\(\) \?\? ''\}/)
  })

  it('targets a path vite maps to jam.html', () => {
    const config = readFileSync(resolve(repo, 'vite.config.ts'), 'utf8')
    expect(config).toContain(
      "const JAM_PATHS = new Set(['/jam', '/jam-rooms'])",
    )
    expect(config).toContain("JAM_PATHS.has(path)) req.url = '/jam.html'")
  })
})

// ============================================================
// The Ear Lab entry lands on the bench, not on Home
// ============================================================
//
// Same shape as Jam: the Lab is a tab of the studio, so /ear-lab is a real
// page for crawlers and unfurlers that boots the studio and sets the hash.
describe('the ear lab entry', () => {
  it('lands on the Ear Lab tab', () => {
    expect(read('ear-lab.html')).toContain("window.location.hash = '#/ear-lab'")
    expect(parseHash('#/ear-lab')).toEqual({ type: 'tab', tab: 'ear-lab' })
  })
  it('targets a path vite maps to ear-lab.html', () => {
    const config = readFileSync(resolve(repo, 'vite.config.ts'), 'utf8')
    expect(config).toContain("const EAR_LAB_PATHS = new Set(['/ear-lab'])")
    expect(config).toContain(
      "EAR_LAB_PATHS.has(path)) req.url = '/ear-lab.html'",
    )
    expect(config).toContain("earLab: resolve(__dirname, 'ear-lab.html')")
  })
  it('is listed in the sitemap', () => {
    expect(readFileSync(resolve(repo, 'public/sitemap.xml'), 'utf8')).toContain(
      '<loc>https://mercurypitch.com/ear-lab</loc>',
    )
  })
})
