"""Build a local audition page for the archived owner-provided Suno takes."""
from pathlib import Path
from html import escape
from urllib.parse import quote
import json
HERE=Path(__file__).resolve().parent
d=json.loads((HERE/'intake.json').read_text())
roles={'M01':'Main museum exploration','M02':'Hidden balcony and quieter exploration','M03':'Playful traversal variation','M04':'Welcome and tutorial','M05':'Level completion reward','M06':'Future moonlit gallery variation','A01':'Air between the columns','A02':'Garden water and stone','A03':'Quiet glass gallery'}
cards=[]
for r in sorted(d['tracks'], key=lambda row:(0 if row['id'].startswith('M') else 1,row['id'],row['take'])):
 seconds=round(float(r['format']['duration']));duration=f'{seconds//60}:{seconds%60:02d}'
 gain=r.get('audition',{}).get('gainDb');target=r.get('audition',{}).get('targetLufs')
 label=f"{r['id']} · {r['title']}"+(f" · {r['take'].upper()}" if r['id']=='A03' else '')
 note='Loop editing needed; this is a short complete take.' if r['id'].startswith('A') else 'Full take; final gameplay edit and placement pending.'
 cards.append(f'<article id="{r["id"]}-{r["take"]}"><p class="role">{escape(roles[r["id"]])}</p><h2>{escape(label)}</h2><p class="meta">{duration} · 48 kHz stereo WAV master · preview {target} LUFS</p><audio controls preload="metadata" src="{quote(r["preview"])}" aria-label="Play {escape(label,quote=True)}"></audio><p class="note">{note}</p><details><summary>Source and audio checks</summary><p>Full decode passed. Original {r["loudness"]["input_i"]} LUFS, peak {r["loudness"]["input_tp"]} dBTP. Preview gain {gain} dB; dynamics preserved. Original WAV is byte-identical to the download.</p><a href="{quote(r["master"])}">Original WAV</a> · <a href="{quote(r["preview"])}">MP3 audition</a></details></article>')
page="""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Glassworks music auditions</title><style>
:root{color-scheme:light;color:#193b42;background:#e9efed;font:16px/1.55 'Trebuchet MS',Arial,sans-serif}*{box-sizing:border-box}body{margin:0}main{max-width:1100px;padding:40px 28px 70px;margin:auto}a{color:#145966;text-underline-offset:4px}h1{font-size:clamp(35px,5vw,58px);letter-spacing:-.04em;line-height:1.05;margin:18px 0}h2{font-size:23px;line-height:1.25;margin:4px 0 12px}p{max-width:76ch;margin:10px 0}.intro{font-size:18px}.notice{border-left:4px solid #8b723e;background:#f5f0dd;padding:14px 18px;margin:24px 0 30px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}article{min-width:0;background:#fff;padding:24px;border-top:3px solid #a0babc}.role{text-transform:uppercase;letter-spacing:.07em;font-size:12px;color:#6d652f}.meta,.note,details{font-size:14px;color:#4c6970}audio{display:block;width:100%;margin:18px 0}details{border-top:1px solid #d3dfdf;margin-top:16px;padding-top:14px}summary{cursor:pointer;min-height:32px}:focus-visible{outline:3px solid #91712b;outline-offset:4px}footer{margin-top:30px;font-size:14px}@media(max-width:680px){main{padding:24px 16px 50px}.grid{grid-template-columns:1fr}article{padding:20px}}
</style></head><body><main><a href="../../v3/review.html">Back to museum artwork</a><h1>A little life<br>between the glass.</h1><p class="intro">Ten owner-provided Suno takes, with original WAVs preserved and smaller level-matched MP3 auditions. Start with M01 for exploration, then compare the ambient beds. Both A03 variants are retained.</p><div class="notice"><strong>Auditions only; not yet playing in the game.</strong><p>Music previews target −20 LUFS and ambience −28 LUFS using a constant gain change. No dynamic compression, musical edits or loop seams have been added. In the game, music and ambience will fade out before voice listening unless the player explicitly chooses a quiet headphone mix.</p></div><div class="grid">"""+''.join(cards)+"""</div><footer><p><a href="README.md">Intake and next steps</a> · <a href="intake.json">Source hashes and measured levels</a></p></footer></main><script>document.querySelectorAll('audio').forEach(player=>player.addEventListener('play',()=>document.querySelectorAll('audio').forEach(other=>{if(other!==player)other.pause()})))</script></body></html>"""
(HERE/'review.html').write_text(page)
print(json.dumps({'tracks':len(cards),'page':str(HERE/'review.html')}))
