// Generated by scripts/gen-og-versions.mjs — do not edit by hand.
//
// Eight hex characters of each card's SHA-256, spent as a `?v=` on its public
// URL so a regenerated card is a new link to every social cache. Regenerate a
// card, run the script, commit both.

export const OG_IMAGE_VERSIONS: Readonly<Record<string, string>> = {
  'drum-night-og.png': '6adf029e',
  'ear-lab-og.png': 'f29419ce',
  'guitar-night-og.png': '636eed8d',
  'jam-og.png': '9324f873',
  'karaoke-og.png': '04c47730',
  'mirror-og.png': '1fc7d97d',
  'og-image.png': '411005dd',
  'piano-night-og.png': 'abfdb130',
  'pitch-training-og.png': '1319ce30',
  'vocal-range-test-og.png': 'd21ec3e8',
  'voice-type-test-og.png': '7ff4f5d0',
  'which-singer-has-my-vocal-range-og.png': '977ae3d2',
  'glass/og.jpg': 'b1495474',
}
