// ============================================================
// Legacy CSS fallbacks — make `color-mix()` degrade instead of vanish
// ============================================================
//
// `color-mix()` needs Chrome 111 / Safari 16.2. Television browsers are years
// behind that: the Android TV WebView on a 2020 Philips set is Chrome 83, LG's
// webOS shell is Chrome 79. A browser that cannot parse a value drops the whole
// declaration, so on those devices every one of the ~490 `color-mix()` calls in
// this app silently disappears — which is why the A/B loop buttons render grey
// instead of blue and red, and why accent tints, glows and hover states are
// missing across the TV UI.
//
// This runs as a Vite `enforce: 'pre'` transform, so it sees plain authored CSS
// before Lightning CSS minifies it, and emits a preceding fallback declaration:
//
//   background: rgba(var(--accent-rgb), 0.16);          <- added
//   background: color-mix(in srgb, var(--accent) 16%, transparent);
//
// Old browsers keep the first (they cannot parse the second); new browsers take
// the second, so nothing changes for them. The `--accent-rgb` companions are
// generated by the same pass from every literal colour custom property, in the
// rule that declared them — so theme switching keeps working.
//
// Deliberately conservative: anything it cannot resolve exactly is left alone,
// which is the current behaviour, not a regression.
//
// Tests: tools/css-legacy-fallbacks.test.ts
// ============================================================

interface Rgb {
  r: number
  g: number
  b: number
}

/** The only named colours worth resolving; everything else is left alone. */
const NAMED_COLORS: Record<string, Rgb> = {
  white: { r: 255, g: 255, b: 255 },
  black: { r: 0, g: 0, b: 0 },
  red: { r: 255, g: 0, b: 0 },
  silver: { r: 192, g: 192, b: 192 },
  gray: { r: 128, g: 128, b: 128 },
  grey: { r: 128, g: 128, b: 128 },
}

const clampByte = (value: number): number =>
  Math.max(0, Math.min(255, Math.round(value)))

/** Parse a literal colour to RGB. Returns null for anything with a `var()`. */
export function parseLiteralColor(input: string): Rgb | null {
  const value = input.trim().toLowerCase()
  if (value === '') return null

  const named = NAMED_COLORS[value]
  if (named) return named

  const hex = /^#([0-9a-f]{3,8})$/.exec(value)
  if (hex) {
    const digits = hex[1]
    if (digits.length === 3 || digits.length === 4) {
      return {
        r: parseInt(digits[0] + digits[0], 16),
        g: parseInt(digits[1] + digits[1], 16),
        b: parseInt(digits[2] + digits[2], 16),
      }
    }
    if (digits.length === 6 || digits.length === 8) {
      return {
        r: parseInt(digits.slice(0, 2), 16),
        g: parseInt(digits.slice(2, 4), 16),
        b: parseInt(digits.slice(4, 6), 16),
      }
    }
    return null
  }

  const rgb = /^rgba?\(([^)]*)\)$/.exec(value)
  if (rgb) {
    const parts = rgb[1]
      .split(/[\s,/]+/)
      .map((part) => part.trim())
      .filter((part) => part !== '')
    if (parts.length < 3) return null
    const channels = parts.slice(0, 3).map((part) => {
      if (part.endsWith('%')) return (parseFloat(part) / 100) * 255
      return parseFloat(part)
    })
    if (channels.some((channel) => !Number.isFinite(channel))) return null
    return {
      r: clampByte(channels[0]),
      g: clampByte(channels[1]),
      b: clampByte(channels[2]),
    }
  }

  return null
}

/** Split on top-level commas — `var(--a, #fff)` must stay in one piece. */
function splitTopLevel(input: string, separator: string): string[] {
  const parts: string[] = []
  let depth = 0
  let start = 0
  for (let i = 0; i < input.length; i++) {
    const ch = input[i]
    if (ch === '(') depth++
    else if (ch === ')') depth--
    else if (ch === separator && depth === 0) {
      parts.push(input.slice(start, i))
      start = i + 1
    }
  }
  parts.push(input.slice(start))
  return parts.map((part) => part.trim())
}

interface ColorTerm {
  /** The colour expression with its percentage stripped off. */
  color: string
  /** 0–1, or null when the author left it implicit. */
  weight: number | null
}

function parseColorTerm(input: string): ColorTerm | null {
  const trimmed = input.trim()
  if (trimmed === '') return null
  // The percentage may lead or trail: `red 30%` and `30% red` are both legal.
  const trailing = /^(.*?)\s+(-?[\d.]+)%$/.exec(trimmed)
  if (trailing) {
    return { color: trailing[1].trim(), weight: parseFloat(trailing[2]) / 100 }
  }
  const leading = /^(-?[\d.]+)%\s+(.*)$/.exec(trimmed)
  if (leading) {
    return { color: leading[2].trim(), weight: parseFloat(leading[1]) / 100 }
  }
  return { color: trimmed, weight: null }
}

const VAR_REFERENCE = /^var\(\s*(--[\w-]+)\s*(?:,\s*([\s\S]+))?\)$/

/**
 * An alpha-tinted version of one colour expression, or null when the value
 * cannot be expressed without `color-mix`.
 *
 * `var(--accent)` becomes `rgba(var(--accent-rgb), a)`; a `var()` that carries
 * its own literal fallback keeps it, so the result is still correct on a
 * browser that never saw the companion token.
 */
export function alphaFallback(color: string, alpha: number): string | null {
  const rounded = Math.round(Math.max(0, Math.min(1, alpha)) * 1000) / 1000
  const literal = parseLiteralColor(color)
  if (literal) {
    return `rgba(${literal.r}, ${literal.g}, ${literal.b}, ${rounded})`
  }

  const reference = VAR_REFERENCE.exec(color.trim())
  if (reference) {
    const token = reference[1]
    if (token.endsWith('-rgb')) return null
    const declaredFallback = reference[2]
    const fallbackRgb =
      declaredFallback === undefined
        ? null
        : parseLiteralColor(declaredFallback)
    const inner =
      fallbackRgb === null
        ? `var(${token}-rgb)`
        : `var(${token}-rgb, ${fallbackRgb.r}, ${fallbackRgb.g}, ${fallbackRgb.b})`
    return `rgba(${inner}, ${rounded})`
  }

  return null
}

const isTransparent = (color: string): boolean =>
  color.trim().toLowerCase() === 'transparent'

/**
 * Resolve one `color-mix(in srgb, A, B)` argument list to a legacy value.
 *
 * Three cases, in order of fidelity:
 *   1. Tinting with `transparent` — exactly reproducible as `rgba()`.
 *   2. Two literal colours — computed numerically, also exact.
 *   3. Anything else — approximated by whichever side dominates the mix, which
 *      keeps the hue family right even though the blend is lost.
 */
function resolveMixArguments(argumentList: string): string | null {
  const parts = splitTopLevel(argumentList, ',')
  if (parts.length !== 3) return null
  if (parts[0].trim().toLowerCase() !== 'in srgb') return null

  const first = parseColorTerm(parts[1])
  const second = parseColorTerm(parts[2])
  if (!first || !second) return null
  if (
    first.color.includes('color-mix(') ||
    second.color.includes('color-mix(')
  ) {
    return null
  }
  if (
    first.color.toLowerCase() === 'currentcolor' ||
    second.color.toLowerCase() === 'currentcolor'
  ) {
    return null
  }

  // Percentages are optional and normalise to 100%; the common authored form
  // gives exactly one of them.
  const firstWeight =
    first.weight ?? (second.weight === null ? 0.5 : 1 - second.weight)
  const secondWeight = second.weight ?? 1 - firstWeight
  if (!Number.isFinite(firstWeight) || !Number.isFinite(secondWeight))
    return null

  if (isTransparent(second.color))
    return alphaFallback(first.color, firstWeight)
  if (isTransparent(first.color))
    return alphaFallback(second.color, secondWeight)

  const firstRgb = parseLiteralColor(first.color)
  const secondRgb = parseLiteralColor(second.color)
  if (firstRgb && secondRgb) {
    const total = firstWeight + secondWeight
    if (total <= 0) return null
    const ratio = firstWeight / total
    return `rgb(${clampByte(firstRgb.r * ratio + secondRgb.r * (1 - ratio))}, ${clampByte(
      firstRgb.g * ratio + secondRgb.g * (1 - ratio),
    )}, ${clampByte(firstRgb.b * ratio + secondRgb.b * (1 - ratio))})`
  }

  // Neither side is resolvable to a number: keep the dominant colour whole.
  const dominant = firstWeight >= secondWeight ? first.color : second.color
  return dominant.includes('color-mix(') ? null : dominant
}

/** Rewrite every `color-mix()` in a declaration value, or null if any resists. */
export function fallbackForValue(value: string): string | null {
  let out = ''
  let index = 0
  let replaced = false

  while (index < value.length) {
    const start = value.indexOf('color-mix(', index)
    if (start === -1) {
      out += value.slice(index)
      break
    }
    out += value.slice(index, start)

    let depth = 0
    let end = -1
    for (let i = start + 'color-mix'.length; i < value.length; i++) {
      if (value[i] === '(') depth++
      else if (value[i] === ')') {
        depth--
        if (depth === 0) {
          end = i
          break
        }
      }
    }
    if (end === -1) return null

    const resolved = resolveMixArguments(
      value.slice(start + 'color-mix('.length, end),
    )
    if (resolved === null) return null
    out += resolved
    replaced = true
    index = end + 1
  }

  return replaced ? out : null
}

interface DeclarationSpan {
  property: string
  value: string
  /** Index of the first character of the property name. */
  start: number
  /** Index one past the last character of the value. */
  end: number
}

/**
 * Find every declaration at rule level. Hand-rolled rather than regex because
 * at-rule preludes (`@supports (color: color-mix(...))`) look exactly like
 * declarations and must never be rewritten.
 */
function scanDeclarations(css: string): DeclarationSpan[] {
  const spans: DeclarationSpan[] = []
  let depth = 0
  let i = 0
  let declarationStart = -1

  const push = (end: number): void => {
    if (declarationStart === -1 || depth === 0) return
    const text = css.slice(declarationStart, end)
    const colon = text.indexOf(':')
    if (colon > 0) {
      const property = text.slice(0, colon).trim()
      const value = text.slice(colon + 1).trim()
      if (property !== '' && !property.includes('{') && value !== '') {
        spans.push({
          property,
          value,
          start: declarationStart + text.indexOf(property),
          end,
        })
      }
    }
    declarationStart = -1
  }

  while (i < css.length) {
    const ch = css[i]
    if (ch === '/' && css[i + 1] === '*') {
      const close = css.indexOf('*/', i + 2)
      i = close === -1 ? css.length : close + 2
      continue
    }
    if (ch === '"' || ch === "'") {
      const quote = ch
      i++
      while (i < css.length && css[i] !== quote) {
        if (css[i] === '\\') i++
        i++
      }
      i++
      continue
    }
    if (ch === '@') {
      // Skip the whole prelude: it can contain a colon and parentheses.
      while (i < css.length && css[i] !== '{' && css[i] !== ';') i++
      declarationStart = -1
      continue
    }
    if (ch === '{') {
      depth++
      declarationStart = -1
      i++
      continue
    }
    if (ch === '}') {
      push(i)
      depth = Math.max(0, depth - 1)
      declarationStart = -1
      i++
      continue
    }
    if (ch === ';') {
      push(i)
      i++
      continue
    }
    if (declarationStart === -1 && !/\s/.test(ch) && depth > 0) {
      declarationStart = i
    }
    i++
  }

  return spans
}

const indentationBefore = (css: string, index: number): string => {
  let start = index
  while (start > 0 && css[start - 1] !== '\n') start--
  return css.slice(start, index)
}

/**
 * Insert `--x-rgb: r, g, b` beside every literal colour custom property, then a
 * legacy fallback before every declaration that uses `color-mix()`.
 */
export function addLegacyColorFallbacks(css: string): string {
  if (!css.includes('color-mix(')) return css

  const spans = scanDeclarations(css)
  const insertions: Array<{ at: number; text: string }> = []
  const companionsSeen = new Set(
    spans
      .filter((span) => span.property.endsWith('-rgb'))
      .map((span) => span.property),
  )

  for (const span of spans) {
    if (span.property.startsWith('--')) {
      const companion = `${span.property}-rgb`
      if (!companionsSeen.has(companion) && !span.property.endsWith('-rgb')) {
        const literal = parseLiteralColor(span.value)
        // `--danger: var(--red)` aliases one token to another; the companion
        // must alias too, or the fallback chain stops at the first indirection.
        const alias = literal ? null : VAR_REFERENCE.exec(span.value.trim())
        const companionValue = literal
          ? `${literal.r}, ${literal.g}, ${literal.b}`
          : alias && !alias[1].endsWith('-rgb')
            ? `var(${alias[1]}-rgb)`
            : null
        if (companionValue !== null) {
          insertions.push({
            at: span.end,
            text: `;\n${indentationBefore(css, span.start)}${companion}: ${companionValue}`,
          })
        }
      }
    }

    if (!span.value.includes('color-mix(')) continue
    // A quoted value is `content: "…"` — text, not colour. Never touch it.
    if (span.value.includes('"') || span.value.includes("'")) continue
    const fallback = fallbackForValue(span.value)
    if (fallback === null) continue
    insertions.push({
      at: span.start,
      text: `${span.property}: ${fallback};\n${indentationBefore(css, span.start)}`,
    })
  }

  if (insertions.length === 0) return css

  // Apply back-to-front so earlier offsets stay valid.
  insertions.sort((a, b) => b.at - a.at)
  let out = css
  for (const insertion of insertions) {
    out = out.slice(0, insertion.at) + insertion.text + out.slice(insertion.at)
  }
  return out
}

export interface LegacyCssFallbacksPlugin {
  name: string
  enforce: 'pre'
  transform: (code: string, id: string) => { code: string; map: null } | null
}

/**
 * Vite plugin wrapper. `enforce: 'pre'` so it runs on authored CSS, ahead of
 * Vite's own CSS pipeline and Lightning CSS.
 */
export function legacyCssFallbacksPlugin(): LegacyCssFallbacksPlugin {
  return {
    name: 'mercurypitch:legacy-css-fallbacks',
    enforce: 'pre',
    transform(code: string, id: string) {
      if (!/\.css(?:$|\?)/.test(id)) return null
      const transformed = addLegacyColorFallbacks(code)
      return transformed === code ? null : { code: transformed, map: null }
    },
  }
}
